### ISSUE TITLE
Connecting to Kafka Topic remotly

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#29]
Hello,

Is it possible to run this adapter on a server other than Kafka installation and connect to the Kafka Instance remotely over TCP. Say, instead of running it on Kafka installation server and connecting to MQ remotely over client, we install it on the server hosting the MQ installation and connect to Kafka Topic remotely over TCP. 

I did a quick POC by having Kafka Installation on Server A(since connector would need the Kafka Classes at runtime), setting up the connector on Server A to connect to a Kafka Topic on Server B. It worked well. Just wanted to verify in case I missed anything here or if I should take care of any further configurations.

Also, how will this connector connect to Kafka Installation over TLS. This application when connects to Kafka Installation would be acting as SSL client and Kafka Installation would be SSL Server.

**Comment by AndrewJSchofield** [comment]
Hi, the connector does connect over the network to the Kafka cluster. It's confusing because it's necessary to have a Kafka component called the Kafka Connect worker in order to run the connector, but the actual Kafka cluster can be somewhere else.

So, you can do Kafka Cluster on servers X, Y, Z, Kafka Connect worker and the connector on server A, and MQ on server Q.

The usual TLS configuration options for Kafka Connect work with the connector. You turn it on with configuration options such as:
ssl.protocol=TLSv1.2
ssl.enabled.protocols=TLSv1.2

If you need to authenticate to Kafka also, you'll need to set the credentials in configuration as well. Read the authentication section of the documentation for your Kafka distribution since each one needs slightly different configuration.

**Comment by SAshish19** [comment]
Hi Andrew,

This is more of a query so I am not raising it as an issue and raising it in an old thread. 

Does the connector also accepts response messages after a message has been published to the Kafka Topic ?

Regards

**Comment by AndrewJSchofield** [comment]
The acknowledgements are automatically handled by the Kafka Connect framework.
