### ISSUE TITLE
Connection problem to broker on OpenShift

### ISSUE THREAD

**Issue by jay999123** [ibm-messaging/kafka-connect-mq-source#39]
Hi,
I'm deploying the connector on openshift platform. Once the pod is up and running, I'm seeing that the connector is not able to connect to kafka broker - 

`WARN [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:725)`

The reason being is, the bootstrap config in distributed.properties is `localhost:9092`.  To override this (to use my broker url i.e., `1.1.2.3:9092`), I provided - 

`
env:
            - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
`
in my *.yaml file. But still I'm getting connection issue. Could you please let me know where am I going wrong/if the ENV variable is proper?

Thanks

**Comment by AndrewJSchofield** [comment]
Hi, how are you running the connector on OpenShift? If it's Strimzi, for example, you need to follow the Strimzi documentation to discover and set the bootstrap servers.

**Comment by jay999123** [comment]
Hi,
I'm already using the Strimzi and it's working fine. But just wanted to run with the docker file provided in this project.

**Comment by katheris** [comment]
Hey @jay999123, the Dockerfile in this project uses the default `connect-distributed.properties` file from Kafka, as in this line: `COPY --chown=esuser:esgroup --from=builder /opt/kafka/config/connect-distributed.properties /opt/kafka/config/`

Since the default `connect-distributed.properties` has `bootstrap.servers=localhost:9092` hard-coded if you want to provide alternative properties you will need to provide a replacement file and for that you have two options.

Either replace the `COPY` line above in the Dockerfile with one that will copy your own properties. e.g. `COPY /path/connect-distributed.properties /opt/kafka/config/`, or you can mount a replacement connect-distributed.properties file into the container using a volume.

I hope that makes sense. The default connect-distributed.properties from Kafka unfortunately does not include a mechanism for adopting environment variables.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue. If you need further help, please re-open.
