### ISSUE TITLE
Message Ordering 

### ISSUE THREAD

**Issue by rkling01** [ibm-messaging/kafka-connect-mq-source#54]
Hi we are using the MQ Source Connector and have a question related to getting messages in physical order from a Queue.

We have a CDC process running on a source system that publishes changes (messages) into MQ and have strict requirements to consume the messages in the physical order they are published.

In terms of connectors and tasks - can you tell me what the scaling limitations are so that I maintain the requirement of getting messages in physical order? 

I am trying to avoid the situation where I would have multiple threads consuming messages from MQ if we scale number of tasks etc. and even though messages are being consumed in order on the queue one of the threads might publish faster and potentially publish a message out of order into the kafka topic.  I'm not 100% sure if this is a scenario that would happen so just trying to validate.  We haven't seen this occur yet in our limited testing. 

On the publisher side, we are publishing messages to Kafka using message keys and using a Connect SMT (valueToKey) transformation to from a unique key field in the message header  guarantee order in Kafka for the consumer.  

When I read your write up in Medium - I realized that we may see an occasional duplicate message which could impact order if two changes very near each other happened on the same key and a republish occurred to due a cluster or network issue.    Any insight would be very helpful.  Thanks!

**Comment by AndrewJSchofield** [comment]
Hi, as you can probably tell from reading my Medium article, I do have to worry a lot about ordering and duplicates for this kind of situation.

I don't think you'll be able to rule out any duplication at all because the connector is based on Kafka Connect. I could write an entirely in-order, no-duplicates connector but it would be much more complicated and slower.

To minimise ordering problems, you should only run a single task on the queue. Otherwise, you'll have multiple tasks consuming competitively from the queue and there is massive risk of out-of-order delivery.

With a single task, you'll generally find that messages are delivered exactly-once and in order. However, because the consumption from MQ and the publication into Kafka is not transactionally coordinated, there is a small chance when the tasks is killed and restarted that messages from MQ which had been published into Kafka will be rolled back onto the queue and then redelivered.

Let's imagine a row in your CDC table that has a Create (C), Update 1 (U1), Update 2 (U2) and then Delete (D). This is going to result in 4 MQ messages, C-U1-U2-D in that order, probably with a bunch of other messages interleaved too. In the normal run of things, you're going to get 4 Kafka records C-U1-U2-D also. However, you could get any repeating subsequences of this too, but the final order will end with the correct sequence, such as C-U1-U2-U1-U2-D. If you idempotently process those Kafka records, you're going to see the final state being D, although there were a few too many U's in there also.

In another example where you want C-U1-U2-U3, you might get C-U1-U2-U2-U3. Again, the end state is U3.

So, I'd design my processing logic to handle this, use each record to *supersede* the previous one in the knowledge that an out-of-order record will shortly be followed by an in-order one.

Hope this helps.

**Comment by rkling01** [comment]
@AndrewJSchofield thanks so much for the reply!  Your details helped and those are exactly some of the scenarios I was thinking about.  Will definitely go with a single task per connector. 

I think the scenario I was most concerned about was an update of a single key in the CDC table (in this case say the update was a Customer Update and the change of address was the update and U1 had a address typo and U2 was the correction and they happened almost simultaneously).  If U1, U2 are processed out of order (U2, U1) it would leave the final state at U1 instead of U2 but since you mentioned that rollback and redelivery on a task failure sounds that would likely not occur.  

I did have a thought that the processing logic (Kafka consumer) would likely need to be idempotent and are designing for that so sounds like that would be sufficient.  Was considering designing for the ability to handle a "stale" (out of order update) as we don't really need all the updates in most cases to be applied, just the most recent for a given key but that does add some complexity and may not be needed based on what we discussed above. 

Thanks again - very much appreciate your feedback!
