### ISSUE TITLE
ByteArrayConverter and Avro Output

### ISSUE THREAD

**Issue by retinaburn** [ibm-messaging/kafka-connect-mq-source#62]
We are currently using kafka-connect-mq-source to consume from MQ and write out EBCDIC bytes to a topic. We are investigating the possibility of writing out the bytes in an Avro message (with the schema pre-registered) however I am having trouble getting it to work.

Relevant properties for our Bytes messages (which works):
"value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"
"mq.record.builder": "com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder"
"mq.message.body.jms": "true"

When I try to use value.converter as the AvroConverter (with the schema.registry.url) but we get an error:
Executing stage 'VALUE_CONVERTER' with class 'io.confluent.connect.avro.AvroConverter', where source record is ......value=[B@2w1de971.....
org.apache.kafka.connect.errors.DataException: Unknown Java type for schemaless data: class [B

Any suggestions?

**Comment by AndrewJSchofield** [comment]
What you will need to do is get the intermediate SourceRecord to have a structure that's compatible with the capabilities of the AvroConverter. I do have a plan to write an article on using the connector with a schema registry since I think it will take me a bit of experimentation to get it working nicely. Definitely possible, but you'll have to get the settings just right. The particular difficulty you have here is that the data comes in as EBCDIC. I expect you want that converted to Unicode, and that's one of the things that `mq.message.body.jms=true` is doing for you.

**Comment by retinaburn** [comment]
Thanks @AndrewJSchofield should I look at extending the DefaultRecordBuilder then for my own purposes?

**Comment by AndrewJSchofield** [comment]
Yes, I think that's a good approach.

**Comment by retinaburn** [comment]
Thanks @AndrewJSchofield

**Comment by VenkatJav** [comment]
how did you resolve this issue? 
I'm getting same error "Caused by: org.apache.kafka.connect.errors.DataException: Unknown Java type for schemaless data: class [B" with below config having value.converter.schema.registry.url
         "mq.record.builder": "com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder",
        "mq.message.body.jms": "true",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
