### ISSUE TITLE
Event ordering in case of multiple workers added for same MQ queue

### ISSUE THREAD

**Issue by abhishek0589** [ibm-messaging/kafka-connect-mq-source#75]
Hello Andrew- I am looking for details on the behavior of the MQ connector in distributed mode when there are multiple workers acting on the same queue and publishing to same topic. In such a case, would workers retain the order of events being recieved while publishing to the topic?

**Comment by AndrewJSchofield** [comment]
Hi. No, they would not. Ordering would not be maintained with multiple tasks on the same queue.

**Comment by abhishek0589** [comment]
Thank you for getting back. Is this a general limitation with *any* source/sink connector in distributed mode or is specific to IBM MQ connector?

**Comment by AndrewJSchofield** [comment]
It is a general limitation with the majority of source connectors. The problem here is that you are taking an ordered sequence of messages on a queue, and if you have multiple consuming tasks, they cannot re-assemble the same order of messages on the target system. You'll just get a jumble.

If the source system had some kind of ordering key and you could insert records from a number of concurrent tasks maintaining the ordering key on the target system, the tasks could potentially merge their messages as they arrived. MQ doesn't work like that.

**Comment by rkling01** [comment]
Just wanted to share we had a similar requirement and https://github.com/ibm-messaging/kafka-connect-mq-source/issues/54 that @AndrewJSchofield and I had discussed a similar scenario if it helps.  Same direction where we ended up running with single tasks per queue which does limit scalability a bit but we didn't have any of the ordering details on the messages in MQ as they were published available.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
