### ISSUE TITLE
Pause connector does'nt stop tasks in connector

### ISSUE THREAD

**Issue by benjaminretore** [ibm-messaging/kafka-connect-mq-source#84]
When I send a curl for stop connector source MQ (http://server:port/connectors/{connectorname}/pause), I got this status : 

`{
    "name": "bel_sia_wms_connector_source_mq",
    "connector": {
        "state": "PAUSED",
        "worker_id": "10.33.27.18:8083"
    },
    "tasks": [
        {
            "id": 0,
            "state": "RUNNING",
            "worker_id": "10.33.27.18:8083"
        }
    ],
    "type": "source"
}`

API rest have not stop command for task. 
Do you have a solution? I want stop the connector for delete all message in the topic.

**Comment by pierre-degrandmaison** [comment]
Any updates? Look like there are several isssues related this "sticky MQ connection" one. I requested an IBM support PMR to be openned, this issue has a major impact as it "steals" MQ messages from the sourced queue until we force the whole Kafka Connect cluster to shutdown.

**Comment by Joel-hanson** [comment]
Hello @benjaminretore and @pierre-degrandmaison,

I sincerely apologize for the prolonged delay in resolving this issue. I want to assure you that we are actively investigating the problem and working towards a solution. Rest assured, we will provide an update as soon as we are able to resolve it.

Thank you for your patience and understanding.

**Comment by Joel-hanson** [comment]
Hi @benjaminretore,

You shouldn't use some REST API features when using the KafkaConnector resource and the connection operator. Pausing is one of these features. This is because the KafkaConnetor resources are the only source of truth for the connector user, who will then unpause the connector. So, to stop the connector, you should change the KAfkaConnector resource and set `pause: true` (https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaConnectorSpec-reference).

You could look at https://github.com/strimzi/strimzi-kafka-operator/issues/3277 to find an answer to a similar question.

**Comment by AishD3** [comment]
@Joel-hanson is it fixed now

**Comment by Joel-hanson** [comment]
@AishD3 The latest version of the connector fixes this issue, could you please try using this https://github.com/ibm-messaging/kafka-connect-mq-source/releases/tag/v1.3.3
